[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/tej/Documents/CNH/DockerImages/glxgears/code/warehouse_autonomous_robo_picker/build/ros2_aruco/.pytest_cache
rootdir: /home/tej/Documents/CNH/DockerImages/glxgears/code/warehouse_autonomous_robo_picker/src/ros2_aruco
plugins: launch-testing-ros-0.19.6, launch-testing-1.0.4, ament-pep257-0.12.9, ament-flake8-0.12.9, ament-lint-0.12.9, ament-xmllint-0.12.9, ament-copyright-0.12.9, cov-3.0.0, colcon-core-0.15.1
[1mcollecting ... [0m[1m
collected 3 items                                                              [0m

test/test_copyright.py [31mF[0m[31m                                                 [ 33%][0m
test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
test/test_pep257.py [31mF[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m________________________________ test_copyright ________________________________[0m
[1m[31mtest/test_copyright.py[0m:23: in test_copyright
    [94massert[39;49;00m rc == [94m0[39;49;00m, [33m'[39;49;00m[33mFound errors[39;49;00m[33m'[39;49;00m
[1m[31mE   AssertionError: Found errors[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stderr call -----------------------------
launch/aruco_recognition.launch.py: could not find copyright notice
ros2_aruco/aruco_generate_marker.py: could not find copyright notice
ros2_aruco/aruco_node.py: could not find copyright notice
3 errors, checked 7 files
[31m[1m_________________________________ test_flake8 __________________________________[0m
[1m[31mtest/test_flake8.py[0m:23: in test_flake8
    [94massert[39;49;00m rc == [94m0[39;49;00m, [33m'[39;49;00m[33mFound errors[39;49;00m[33m'[39;49;00m
[33m=============================== warnings summary ===============================[0m
test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
[1m[31mE   AssertionError: Found errors[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------

./launch/aruco_recognition.launch.py:6:1: E302 expected 2 blank lines, found 1
def generate_launch_description():
^

./ros2_aruco/aruco_generate_marker.py:15:1: D204 1 blank line required after class docstring
    """ Trick to allow both defaults and nice formatting in the help. """
^

./ros2_aruco/aruco_generate_marker.py:15:1: D210 No whitespaces allowed surrounding docstring text
    """ Trick to allow both defaults and nice formatting in the help. """
^

./ros2_aruco/aruco_node.py:121:36: E721 do not compare types, use 'isinstance()'
            if type(dictionary_id) != type(cv2.aruco.DICT_5X5_100):
                                   ^

1     D204 1 blank line required after class docstring
1     D210 No whitespaces allowed surrounding docstring text
1     E302 expected 2 blank lines, found 1
1     E721 do not compare types, use 'isinstance()'

8 files checked
4 errors

'D'-type errors: 2
'E'-type errors: 2

Checked files:

* ./setup.py
* ./launch/aruco_recognition.launch.py
* ./test/test_pep257.py
* ./test/test_flake8.py
* ./test/test_copyright.py
* ./ros2_aruco/aruco_generate_marker.py
* ./ros2_aruco/__init__.py
* ./ros2_aruco/aruco_node.py
----------------------------- Captured stderr call -----------------------------
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
[31m[1m_________________________________ test_pep257 __________________________________[0m
[1m[31mtest/test_pep257.py[0m:23: in test_pep257
    [94massert[39;49;00m rc == [94m0[39;49;00m, [33m'[39;49;00m[33mFound code style errors / warnings[39;49;00m[33m'[39;49;00m
[1m[31mE   AssertionError: Found code style errors / warnings[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------
checking ./launch/aruco_recognition.launch.py
checking ./ros2_aruco/__init__.py
checking ./ros2_aruco/aruco_generate_marker.py
./ros2_aruco/aruco_generate_marker.py:15 in public class `CustomFormatter`: D204: 1 blank line required after class docstring (found 0)
./ros2_aruco/aruco_generate_marker.py:15 in public class `CustomFormatter`: D210: No whitespaces allowed surrounding docstring text
checking ./ros2_aruco/aruco_node.py
./ros2_aruco/aruco_node.py:1 at module level: D407: Missing dashed underline after section ('Parameters')
./ros2_aruco/aruco_node.py:1 at module level: D406: Section name should end with a newline ('Parameters', not 'Parameters:')
checking ./setup.py
checking ./test/test_copyright.py
checking ./test/test_flake8.py
checking ./test/test_pep257.py
checking test/test_copyright.py
checking test/test_flake8.py
checking test/test_pep257.py
4 errors
- generated xml file: /home/tej/Documents/CNH/DockerImages/glxgears/code/warehouse_autonomous_robo_picker/build/ros2_aruco/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_copyright.py::test_copyright - AssertionError: Found errors
FAILED test/test_flake8.py::test_flake8 - AssertionError: Found errors
FAILED test/test_pep257.py::test_pep257 - AssertionError: Found code style er...
[31m======================== [31m[1m3 failed[0m, [33m2 warnings[0m[31m in 0.22s[0m[31m =========================[0m
